name: product
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+1

environment:
  sdk: ">=2.3.0 <3.0.0"
  # sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  location: 3.0.1
  google_maps_flutter: 0.5.31
  geocoder: ^0.2.1
  smooth_star_rating: ^1.0.3
  flutter_speed_dial: ^1.2.1
  stripe_payment:
  shared_preferences: 0.5.4+5
  rxdart: 0.24.1
  http: ^0.12.0+1
  firebase_auth: 0.18.2
  auto_size_text: 2.1.0
  google_maps_webservice: ^0.0.14
  flutter_google_places: ^0.2.3
  geolocator: ^5.0.0
  transformer_page_view: 0.1.6
  url_launcher: 5.4.10
  firebase_messaging: ^5.0.4
  notifier: 1.0.2
  fluttertoast: 4.0.1
  carousel_slider: 2.2.1
  flutter_polyline_points: ^0.1.0
  razorpay_flutter: 1.2.2
  flutter_local_notifications: 1.4.4+4
  sms_otp_auto_verify:
  progressive_image:
  country_code_picker: 1.4.0
  flutter_facebook_login: 3.0.0
  google_sign_in: 4.5.4
  image_picker: 0.6.7+4
  image:
  flutter_braintree: 1.1.0
  share: 0.6.5+4
  flutter_launcher_icons: ^0.8.0




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "Assets/doobi.png"


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - Assets/imgLogo.png
   - Assets/FoodZoneLogo.png
   - Assets/doobi.png
   - Assets/googlePlus.png
   - Assets/facebook.png
   - Assets/Dashboard/biryani.jpeg
   - Assets/Dashboard/googleMap.png
   - Assets/RestaurantDetails/RestaurantApp.jpg
   - Assets/RestaurantDetails/profileImage.jpg
   - Assets/RestaurantDetails/vegFood.jpg
   - Assets/RestaurantDetails/veg.png
   - Assets/RestaurantDetails/nonVeg.png
   - Assets/res.jpeg
   - Assets/food.jpeg
   - Assets/jacMa.jpg
   - Assets/nonVeg.png
   - Assets/offer.png
   - Assets/map.png
   - Assets/Checkout/success.png
   - Assets/Checkout/razorpay.png
   - Assets/Payment/Card.png
   - Assets/Payment/Cod.png
   - Assets/Payment/paypal.png
   - Assets/Payment/coffee.png
   - Assets/images/chef.png
   - Assets/images/BegingPrepared.jpg
   - Assets/images/Ober.png
   - Assets/images/lockedAccess.png
   - Assets/images/foodTruck.png
   - Assets/Language/localization_en.json
   - Assets/Language/localization_fr.json
   - Assets/Language/localization_ar.json
   - Assets/Cart/emptyCart.png
   - Assets/images/dataNotFound.png
   - Assets/images/bell.png
   - Assets/images/mail.png
   - Assets/error.png
   - Assets/Onboarding/board_1.png
   - Assets/Onboarding/board_2.png
   - Assets/Onboarding/board_3.png
   - Assets/DoobiAssets/
   - Assets/DoobiAssets/banner/
   - Assets/flags/brazil.png
   - Assets/flags/canada.png
   - Assets/flags/spain.png
   - Assets/flags/uae.png
   - Assets/flags/usa.png
   - Assets/changePassword/passwordSuccess.png
   - Assets/TrackOrder/car.png
   - Assets/TrackOrder/destination_map.png
   - Assets/Banner/banner1.png
   - Assets/Banner/banner2.png
   - Assets/Banner/banner3.jpg
   - Assets/loading.gif
   - Assets/Banner/ch_banner1.jpg
   - Assets/Banner/ch_banner2.jpg
   - Assets/Banner/ch_banner3.jpg
   - Assets/DoobiAssets/


  #  emptyCart
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Quicksand
      fonts:
        - asset: Assets/Font/Quicksand-Bold.ttf
        - asset: Assets/Font/Quicksand-Light.ttf
        - asset: Assets/Font/Quicksand-Medium.ttf
        - asset: Assets/Font/Quicksand-Regular.ttf
          weight: 700
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
          # style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
